### PR TITLE
Remove non-existent builtins and keywords

### PR DESCRIPTION
**Pull request by Someon1e**
https://luau-lang.org/compatibility

### CODE REVIEW

**Comment by joshgoebel** [comment]
Are these mistakes or just only apply to older versions of the language?

**Comment by Someon1e** [comment]
> Are these mistakes or just only apply to older versions of the language?

The ones I removed have never existed in Luau.

**Comment by Hexcede** [comment]
> Are these mistakes or just only apply to older versions of the language?

With the exception of `string.dump` which was removed from Roblox at some point, I think probably before luau came about, all of that stuff hasn't existed in luau. `goto` is from lua 5.3 iirc, while luau is based on lua 5.1 and does have backwards compatible backports from lua 5.3 but doesn't implement any of the lower level language features. The rest of the APIs don't exist in luau since it's a very sandboxed language, it's not intended to have access to any operating system stuff out of the box.

**Review by robloxiandemo — APPROVED** [review]
LGTM! 👍

**Review by robloxiandemo — APPROVED** [review]
LGTM! 👍

**Review by robloxiandemo — APPROVED** [review]
LGTM! 👍

**Review by robloxiandemo — APPROVED** [review]
LGTM! 👍

**Pull request merged**
